spring:
  datasource:
    url: jdbc:mysql:///springmvc
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      
server:
  port: 80
  tomcat:
    uri-encoding: UTF8 